# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

muLmsCpp <- function(model, z) {
    .Call('_cavaan_muLmsCpp', PACKAGE = 'cavaan', model, z)
}

sigmaLmsCpp <- function(model, z) {
    .Call('_cavaan_sigmaLmsCpp', PACKAGE = 'cavaan', model, z)
}

muQmlCpp <- function(m, t) {
    .Call('_cavaan_muQmlCpp', PACKAGE = 'cavaan', m, t)
}

sigmaQmlCpp <- function(m, t) {
    .Call('_cavaan_sigmaQmlCpp', PACKAGE = 'cavaan', m, t)
}

calcKronXi <- function(m, t) {
    .Call('_cavaan_calcKronXi', PACKAGE = 'cavaan', m, t)
}

calcBinvCpp <- function(m, t) {
    .Call('_cavaan_calcBinvCpp', PACKAGE = 'cavaan', m, t)
}

dnormCpp <- function(x, mu, sigma) {
    .Call('_cavaan_dnormCpp', PACKAGE = 'cavaan', x, mu, sigma)
}

varZCpp <- function(Omega, Sigma1, numEta) {
    .Call('_cavaan_varZCpp', PACKAGE = 'cavaan', Omega, Sigma1, numEta)
}

ViewModelCreation <- function(model) {
    .Call('_cavaan_ViewModelCreation', PACKAGE = 'cavaan', model)
}

#' Multiply indicators 
#' @param df A data DataFrame
#' @return A NumericVector
#' @export
multiplyIndicatorsCpp <- function(df) {
    .Call('_cavaan_multiplyIndicatorsCpp', PACKAGE = 'cavaan', df)
}

rep_dmvnorm <- function(x, expected, sigma, t) {
    .Call('_cavaan_rep_dmvnorm', PACKAGE = 'cavaan', x, expected, sigma, t)
}

dmvnrm_arma_mc <- function(x, mean, sigma, logd = TRUE) {
    .Call('_cavaan_dmvnrm_arma_mc', PACKAGE = 'cavaan', x, mean, sigma, logd)
}

