# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ViewModelCreation <- function(RModel, theta) {
    .Call(`_cavaan_ViewModelCreation`, RModel, theta)
}

logLikR2Cpp <- function(theta, model) {
    .Call(`_cavaan_logLikR2Cpp`, theta, model)
}

gradLogLikR2Cpp <- function(theta, model) {
    .Call(`_cavaan_gradLogLikR2Cpp`, theta, model)
}

